heat_template_version: 2013-05-23

description: Create a vino slave 

parameters:
  image_name:
    type: string
    description: Name of image to use for server
    default: Ubuntu64-1404-OVS 

  flavor_name:
    type: string
    description: Name Flavor to use for server
    default: m1.small

  key_name:
    type: string
    description: Name of key to inject into server 
    default: key_spandan

  vino_master_ip: 
    type: string
    description: IP Address of VINO Master
    default: 10.12.1.53

resources:
  Server:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor_name }
      image: { get_param: image_name }
      key_name: { get_param: key_name }
      name: span_node 
      user_data: |
        #!/bin/bash  
        apt-get update
        apt-get install python-dev python-pip wget git -y
        pip install pika==0.9.14
        su - ubuntu -c "git clone https://github.com/spandanb/vino_orc.git /home/ubuntu/vino_orc"
        su - ubuntu -c "wget 'https://raw.githubusercontent.com/spandanb/utils/master/.vimrc' -P /home/ubuntu"
        su - ubuntu -c "wget 'https://raw.githubusercontent.com/spandanb/vino_orc/master/.screenrc' -P /home/ubuntu"
        su - ubuntu -c "screen -AdmS slave" 
outputs:
  public_ip:
    description: The public IP address of the newly configured Server.
    value: { get_attr: [ Server, first_address ] }

