heat_template_version: 2013-05-23

description: Create a vino master

parameters:
  image_name:
    type: string
    description: Name of image to use for server
    default: Ubuntu64-1404-OVS 

  flavor_name:
    type: string
    description: Name Flavor to use for server
    default: m1.small

  key_name:
    type: string
    description: Name of key to inject into server 
    default: key_spandan

resources:
  RyuServer:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor_name }
      image: { get_param: image_name }
      key_name: { get_param: key_name }
      name: ryu_cont 
      user_data: |
        #!/bin/bash  
        apt-get update
        apt-get install python-dev python-pip wget git -y
        pip install pika==0.9.14
        pip install eventlet oslo.config WebOb routes
        git clone git://github.com/osrg/ryu.git
        cd /ryu && python ./setup.py install
        wget https://raw.githubusercontent.com/spandanb/utils/master/.vimrc -P /home/ubuntu
        
        touch /.screenrc
        cat << EOF > /.screenrc
        #General
        screen -t sh
        startup_message off
        hardstatus alwayslastline
        hardstatus string '%{gk}[%{wk}%?%-Lw%?%{=b kR}(%{W}%n*%f %t%?(%u)%?%{=b kR})%{= w}%?%+Lw%?%? %{g}][%{d}%l%{g}][ %{= w}%Y/%m/%d %0C:%s%a%{g} ]%{W}'
        #Run ryu
        select 0
        stuff "cd ./ryu^M"
        stuff "PYTHONPATH=. ./bin/ryu-manager ryu/app/simple_switch.py^M"

        EOF
        sleep 2
        screen -AdmS -c "/.screenrc" vmaster 
        touch /bar
outputs:
  public_ip:
    description: The public IP address of the newly configured Server.
    value: { get_attr: [ RyuServer, first_address ] }

