heat_template_version: 2014-10-16

description: Master Template 
            usage-> heat stack-create -f vino_master2.yaml <name> -P="key_name=<key_name>"
parameters:
  key_name:
    type: string
    description : Name of a KeyPair to enable SSH access to the instance

resources:
  MasterServer:
    type: OS::Nova::Server
    properties:
      flavor:
        m1.medium3
      image:
        master-sdi.0.5
      key_name:
        get_param: key_name
      name: master 
      user_data: 
        str_replace:
          template: |
            #!/usr/bin/env bash
            apt-get update
            su - ubuntu -c "git clone https://github.com/spandanb/vino_orc.git /home/ubuntu/vino_orc"
            su - ubuntu -c "touch /home/ubuntu/vino_orc/params.py"
            su - ubuntu -c "echo \"username='ubuntu'\" >> /home/ubuntu/vino_orc/params.py"
            su - ubuntu -c "echo \"password='savi'\" >> /home/ubuntu/vino_orc/params.py"
            su - ubuntu -c "echo \"host_1='host1_ip'\" >> /home/ubuntu/vino_orc/params.py"

            touch /home/ubuntu/.screenrc
            cat << EOF > /home/ubuntu/.screenrc
            #General
            startup_message off
            hardstatus alwayslastline
            hardstatus string '%{gk}[%{wk}%?%-Lw%?%{=b kR}(%{W}%n*%f %t%?(%u)%?%{=b kR})%{= w}%?%+Lw%?%? %{g}][%{d}%l%{g}][ %{= w}%Y/%m/%d %0C:%s%a%{g} ]%{W}'
            #Run Vino Master 
            screen -t vmaster
            select 0
            stuff "cd /home/ubuntu/vino_orc^M"
            stuff "python vinod.py^M"
            EOF
            
            chmod 666 /home/ubuntu/.screenrc
            su - ubuntu -c "wget 'https://raw.githubusercontent.com/spandanb/utils/master/.vimrc' -P /home/ubuntu"
            su - ubuntu -c "screen -AdmS master" 
          params:
            host1_ip: 10.10.10.10 

outputs:
  master_ip:
    description: The IP address of the Master.
    value: { get_attr: [ MasterServer, first_address ] }

